CREATE TABLE codex_session_catalog (
    session_id TEXT PRIMARY KEY NOT NULL,
    rollout_path TEXT UNIQUE NOT NULL,
    rollout_file_identity TEXT NOT NULL,
    rollout_length BIGINT NOT NULL,
    scan_offset BIGINT NOT NULL,
    created_at_unix_ms BIGINT,
    rollout_updated_at_unix_ms BIGINT NOT NULL,
    rollout_modified_at_unix_ns BIGINT NOT NULL,
    title TEXT,
    title_from_user_message BOOL NOT NULL,
    latest_user_message TEXT,
    latest_user_message_at_unix_ms BIGINT,
    latest_agent_message TEXT,
    latest_agent_message_at_unix_ms BIGINT,
    cwd TEXT,
    model TEXT,
    cli_version TEXT,
    turn_count BIGINT NOT NULL,
    command_count BIGINT NOT NULL,
    file_change_count BIGINT NOT NULL,
    input_tokens BIGINT NOT NULL,
    cached_input_tokens BIGINT NOT NULL,
    output_tokens BIGINT NOT NULL,
    reasoning_output_tokens BIGINT NOT NULL
);
