use crate::config::{validate_ssh_host, ClientConfig, ContextKind};
use crate::inventory::{name_counts, ContextInstance};
use anyhow::{bail, Context, Result};
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};
use wt_api::InstanceStatus;

pub fn sync(client_config: &ClientConfig, instances: &[ContextInstance]) -> Result<PathBuf> {
    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .context("HOME is not set")?;
    let ssh_dir = home.join(".ssh");
    let managed_dir = ssh_dir.join("wt");
    ensure_directory(&ssh_dir)?;
    ensure_directory(&managed_dir)?;
    let config_path = managed_dir.join("config");
    let known_hosts_path = managed_dir.join("known_hosts");
    let main_config_path = ssh_dir.join("config");

    let accessible = instances
        .iter()
        .filter(|item| {
            matches!(
                item.instance.status,
                InstanceStatus::Setup | InstanceStatus::Running
            ) && item.instance.ssh.is_some()
        })
        .collect::<Vec<_>>();
    let counts = name_counts(instances);
    let mut config = String::from("# Generated by wt sync. Do not edit.\n");
    let mut known_hosts = String::from("# Generated by wt sync. Do not edit.\n");
    for item in accessible {
        let instance = &item.instance;
        let ssh = instance.ssh.as_ref().expect("filtered SSH access");
        if ssh.host_keys.is_empty() {
            bail!("instance {} has incomplete SSH host keys", instance.name);
        }
        let qualified = item.qualified_name();
        let context = client_config
            .context(&item.context)
            .with_context(|| format!("missing client context {}", item.context))?;
        let proxy_jump = match &context.kind {
            ContextKind::BareMetalLocal => String::new(),
            ContextKind::BareMetalSsh { host } => {
                validate_ssh_host(&context.name, host)?;
                format!("  ProxyJump {host}\n")
            }
        };
        let guest_common = format!(
            "  HostName {}\n  User {}\n  Port {}\n  HostKeyAlias {}\n  UserKnownHostsFile {}\n  StrictHostKeyChecking yes\n  SetEnv TERM=xterm-256color\n{}",
            ssh.host,
            ssh.user,
            ssh.port,
            format_args!("{qualified}-host"),
            ssh_quote(&known_hosts_path),
            proxy_jump,
        );
        let app_common = instance.app_ssh.as_ref().map(|app_ssh| format!(
            "  HostName wt-app\n  User {}\n  Port {}\n  HostKeyAlias {}-vs\n  UserKnownHostsFile {}\n  StrictHostKeyChecking yes\n  SetEnv TERM=xterm-256color\n  ProxyCommand ssh -F {} {}-host /usr/local/bin/wt-app-proxy\n",
            app_ssh.user,
            app_ssh.port,
            qualified,
            ssh_quote(&known_hosts_path),
            ssh_quote(&main_config_path),
            qualified,
        ));
        let forward_agent = if instance.status == InstanceStatus::Setup {
            "  ForwardAgent yes\n"
        } else {
            ""
        };
        config.push_str(&format!("\nHost {qualified}-host\n{guest_common}\nHost {qualified}\n{guest_common}{forward_agent}  RequestTTY force\n  RemoteCommand /usr/local/bin/wt-app-shell\n"));
        if let Some(app_common) = &app_common {
            config.push_str(&format!("\nHost {qualified}-vs\n{app_common}"));
        }
        if counts.get(instance.name.as_str()) == Some(&1) {
            config.push_str(&format!("\nHost {}-host\n{guest_common}\nHost {}\n{guest_common}{forward_agent}  RequestTTY force\n  RemoteCommand /usr/local/bin/wt-app-shell\n", instance.name, instance.name));
            if let Some(app_common) = &app_common {
                config.push_str(&format!("\nHost {}-vs\n{app_common}", instance.name));
            }
        }
        for key in &ssh.host_keys {
            let mut fields = key.split_whitespace();
            let kind = fields.next().unwrap_or_default();
            let data = fields.next().unwrap_or_default();
            if kind.is_empty() || data.is_empty() {
                bail!("instance {} has an invalid SSH host key", instance.name);
            }
            known_hosts.push_str(&format!("{qualified}-host {kind} {data}\n"));
        }
        let app_known_name = format!("{qualified}-vs");
        for key in instance.app_ssh.iter().flat_map(|ssh| &ssh.host_keys) {
            let mut fields = key.split_whitespace();
            let kind = fields.next().unwrap_or_default();
            let data = fields.next().unwrap_or_default();
            if kind.is_empty() || data.is_empty() {
                bail!("instance {} has an invalid app SSH host key", instance.name);
            }
            known_hosts.push_str(&format!("{app_known_name} {kind} {data}\n"));
        }
    }
    atomic_write(&config_path, config.as_bytes())?;
    atomic_write(&known_hosts_path, known_hosts.as_bytes())?;
    Ok(config_path)
}

fn ensure_directory(path: &Path) -> Result<()> {
    fs::create_dir_all(path).with_context(|| format!("create {}", path.display()))?;
    fs::set_permissions(path, fs::Permissions::from_mode(0o700))
        .with_context(|| format!("set permissions on {}", path.display()))
}

fn atomic_write(path: &Path, contents: &[u8]) -> Result<()> {
    let temporary = path.with_extension("wt-new");
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(&temporary)
        .with_context(|| format!("create {}", temporary.display()))?;
    let result = (|| {
        file.write_all(contents)?;
        file.sync_all()?;
        fs::rename(&temporary, path)?;
        Ok::<_, std::io::Error>(())
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    result.with_context(|| format!("atomically update {}", path.display()))
}

fn ssh_quote(path: &Path) -> String {
    format!(
        "\"{}\"",
        path.display()
            .to_string()
            .replace('\\', "\\\\")
            .replace('\"', "\\\"")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Context as ClientContext, ContextKind};
    use std::sync::Mutex;
    use uuid::Uuid;
    use wt_api::{AppSshAccess, Instance, InstanceName, SshAccess};

    static HOME_LOCK: Mutex<()> = Mutex::new(());

    fn local_config() -> ClientConfig {
        ClientConfig {
            contexts: vec![ClientContext {
                name: "local".into(),
                kind: ContextKind::BareMetalLocal,
            }],
        }
    }

    fn normalize_home(contents: &str, home: &Path) -> String {
        contents.replace(&home.display().to_string(), "[HOME]")
    }

    #[test]
    fn sync_does_not_touch_main_config_and_removes_stale_worlds() {
        let _lock = HOME_LOCK.lock().unwrap();
        let temp = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", temp.path());
        fs::create_dir(temp.path().join(".ssh")).unwrap();
        let main_config = "Host personal\n  HostName example.test\n";
        fs::write(temp.path().join(".ssh/config"), main_config).unwrap();
        let instance = Instance {
            id: Uuid::new_v4(),
            name: InstanceName::parse("repo-feature").unwrap(),
            owner: "lucas".into(),
            status: InstanceStatus::Running,
            source: "git@example.test:repo.git".into(),
            guest_ip: Some("192.0.2.2".into()),
            last_error: None,
            ssh: Some(SshAccess {
                user: "wt".into(),
                host: "192.0.2.2".into(),
                port: 22,
                host_keys: vec!["ssh-ed25519 AAAATEST guest".into()],
            }),
            app_ssh: Some(AppSshAccess {
                user: "vscode".into(),
                port: 2222,
                host_keys: vec!["ssh-ed25519 AAAAAPPLICATION app".into()],
            }),
        };
        let mut replacement_instance = instance.clone();
        replacement_instance.id = Uuid::new_v4();
        replacement_instance.ssh.as_mut().unwrap().host_keys =
            vec!["ssh-ed25519 AAAAREPLACEMENT guest".into()];
        let client_config = local_config();
        sync(
            &client_config,
            &[ContextInstance {
                context: "local".into(),
                instance,
            }],
        )
        .unwrap();
        let managed = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        insta::assert_snapshot!(
            "unique_world_ssh_config",
            normalize_home(&managed, temp.path())
        );
        sync(
            &client_config,
            &[ContextInstance {
                context: "local".into(),
                instance: replacement_instance,
            }],
        )
        .unwrap();
        let known_hosts = fs::read_to_string(temp.path().join(".ssh/wt/known_hosts")).unwrap();
        insta::assert_snapshot!(known_hosts, @r###"
        # Generated by wt sync. Do not edit.
        local.repo-feature-host ssh-ed25519 AAAAREPLACEMENT
        local.repo-feature-vs ssh-ed25519 AAAAAPPLICATION
        "###);
        sync(&client_config, &[]).unwrap();
        let main = fs::read_to_string(temp.path().join(".ssh/config")).unwrap();
        assert_eq!(main, main_config);
        let managed = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        assert!(!managed.contains("repo-feature"));
    }

    #[test]
    fn setup_world_forwards_agent_without_app_alias() {
        let _lock = HOME_LOCK.lock().unwrap();
        let temp = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", temp.path());
        let instance = Instance {
            id: Uuid::new_v4(),
            name: InstanceName::parse("repo-feature").unwrap(),
            owner: "lucas".into(),
            status: InstanceStatus::Setup,
            source: "git@example.test:repo.git".into(),
            guest_ip: Some("192.0.2.2".into()),
            last_error: None,
            ssh: Some(SshAccess {
                user: "wt".into(),
                host: "192.0.2.2".into(),
                port: 22,
                host_keys: vec!["ssh-ed25519 AAAATEST guest".into()],
            }),
            app_ssh: None,
        };
        sync(
            &local_config(),
            &[ContextInstance {
                context: "local".into(),
                instance,
            }],
        )
        .unwrap();
        let managed = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        insta::assert_snapshot!(
            "setup_world_ssh_config",
            normalize_home(&managed, temp.path())
        );
        let known_hosts = fs::read_to_string(temp.path().join(".ssh/wt/known_hosts")).unwrap();
        insta::assert_snapshot!("setup_world_known_hosts", known_hosts);
    }

    #[test]
    fn duplicate_names_only_receive_qualified_aliases() {
        let _lock = HOME_LOCK.lock().unwrap();
        let temp = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", temp.path());
        let instance = |id, context: &str| ContextInstance {
            context: context.into(),
            instance: Instance {
                id,
                name: InstanceName::parse("same").unwrap(),
                owner: "lucas".into(),
                status: InstanceStatus::Running,
                source: "git@example.test:repo.git".into(),
                guest_ip: Some("192.0.2.2".into()),
                last_error: None,
                ssh: Some(SshAccess {
                    user: "wt".into(),
                    host: "192.0.2.2".into(),
                    port: 22,
                    host_keys: vec!["ssh-ed25519 AAAATEST guest".into()],
                }),
                app_ssh: Some(AppSshAccess {
                    user: "vscode".into(),
                    port: 2222,
                    host_keys: vec!["ssh-ed25519 AAAAAPPLICATION app".into()],
                }),
            },
        };
        let client_config = ClientConfig {
            contexts: vec![
                ClientContext {
                    name: "local".into(),
                    kind: ContextKind::BareMetalLocal,
                },
                ClientContext {
                    name: "lab".into(),
                    kind: ContextKind::BareMetalSsh {
                        host: "wt-server".into(),
                    },
                },
            ],
        };
        sync(
            &client_config,
            &[
                instance(Uuid::new_v4(), "local"),
                instance(Uuid::new_v4(), "lab"),
            ],
        )
        .unwrap();
        let managed = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        insta::assert_snapshot!(
            "duplicate_world_names_ssh_config",
            normalize_home(&managed, temp.path())
        );
        assert!(!temp.path().join(".ssh/config").exists());
    }

    #[test]
    fn remote_world_aliases_jump_through_the_context_host() {
        let _lock = HOME_LOCK.lock().unwrap();
        let temp = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", temp.path());
        let instance = |name: &str, host: &str| ContextInstance {
            context: "lab".into(),
            instance: Instance {
                id: Uuid::new_v4(),
                name: InstanceName::parse(name).unwrap(),
                owner: "lucas".into(),
                status: InstanceStatus::Running,
                source: "git@example.test:repo.git".into(),
                guest_ip: Some(host.into()),
                last_error: None,
                ssh: Some(SshAccess {
                    user: "wt".into(),
                    host: host.into(),
                    port: 22,
                    host_keys: vec!["ssh-ed25519 AAAATEST guest".into()],
                }),
                app_ssh: Some(AppSshAccess {
                    user: "vscode".into(),
                    port: 2222,
                    host_keys: vec!["ssh-ed25519 AAAAAPPLICATION app".into()],
                }),
            },
        };
        let client_config = ClientConfig {
            contexts: vec![ClientContext {
                name: "lab".into(),
                kind: ContextKind::BareMetalSsh {
                    host: "wt-server".into(),
                },
            }],
        };

        sync(
            &client_config,
            &[
                instance("world-one", "192.0.2.10"),
                instance("world-two", "192.0.2.11"),
            ],
        )
        .unwrap();

        let managed = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        insta::assert_snapshot!(
            "remote_worlds_ssh_config",
            normalize_home(&managed, temp.path())
        );
    }
}
