use anyhow::{bail, Context, Result};
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};
use wt_api::{Instance, InstanceStatus};

pub fn sync(instances: &[Instance]) -> Result<PathBuf> {
    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .context("HOME is not set")?;
    let ssh_dir = home.join(".ssh");
    let managed_dir = ssh_dir.join("wt");
    ensure_directory(&ssh_dir)?;
    ensure_directory(&managed_dir)?;
    let config_path = managed_dir.join("config");
    let known_hosts_path = managed_dir.join("known_hosts");

    let running = instances
        .iter()
        .filter(|instance| instance.status == InstanceStatus::Running && instance.ssh.is_some());
    let mut config = String::from("# Generated by wt sync. Do not edit.\n");
    let mut known_hosts = String::from("# Generated by wt sync. Do not edit.\n");
    for instance in running {
        let ssh = instance.ssh.as_ref().expect("filtered SSH access");
        if ssh.host_keys.is_empty() {
            bail!("instance {} has no SSH host keys", instance.name);
        }
        let common = format!(
            "  HostName {}\n  User {}\n  Port {}\n  HostKeyAlias {}\n  UserKnownHostsFile {}\n  StrictHostKeyChecking yes\n",
            ssh.host,
            ssh.user,
            ssh.port,
            instance.name,
            ssh_quote(&known_hosts_path),
        );
        config.push_str(&format!(
            "\nHost {}-host\n{common}\nHost {}\n{common}  RequestTTY force\n  RemoteCommand /usr/local/bin/wt-app-shell\n",
            instance.name, instance.name,
        ));
        let known_name = if ssh.port == 22 {
            instance.name.to_string()
        } else {
            format!("[{}]:{}", instance.name, ssh.port)
        };
        for key in &ssh.host_keys {
            let mut fields = key.split_whitespace();
            let kind = fields.next().unwrap_or_default();
            let data = fields.next().unwrap_or_default();
            if kind.is_empty() || data.is_empty() {
                bail!("instance {} has an invalid SSH host key", instance.name);
            }
            known_hosts.push_str(&format!("{known_name} {kind} {data}\n"));
        }
    }
    atomic_write(&config_path, config.as_bytes())?;
    atomic_write(&known_hosts_path, known_hosts.as_bytes())?;
    Ok(config_path)
}

fn ensure_directory(path: &Path) -> Result<()> {
    fs::create_dir_all(path).with_context(|| format!("create {}", path.display()))?;
    fs::set_permissions(path, fs::Permissions::from_mode(0o700))
        .with_context(|| format!("set permissions on {}", path.display()))
}

fn atomic_write(path: &Path, contents: &[u8]) -> Result<()> {
    let temporary = path.with_extension("wt-new");
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(&temporary)
        .with_context(|| format!("create {}", temporary.display()))?;
    let result = (|| {
        file.write_all(contents)?;
        file.sync_all()?;
        fs::rename(&temporary, path)?;
        Ok::<_, std::io::Error>(())
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    result.with_context(|| format!("atomically update {}", path.display()))
}

fn ssh_quote(path: &Path) -> String {
    format!(
        "\"{}\"",
        path.display()
            .to_string()
            .replace('\\', "\\\\")
            .replace('\"', "\\\"")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use uuid::Uuid;
    use wt_api::{InstanceName, SshAccess};

    #[test]
    fn sync_does_not_touch_main_config_and_removes_stale_worlds() {
        let temp = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", temp.path());
        fs::create_dir(temp.path().join(".ssh")).unwrap();
        let main_config = "Host personal\n  HostName example.test\n";
        fs::write(temp.path().join(".ssh/config"), main_config).unwrap();
        let instance = Instance {
            id: Uuid::new_v4(),
            name: InstanceName::parse("repo-feature").unwrap(),
            owner: "lucas".into(),
            status: InstanceStatus::Running,
            source: "git@example.test:repo.git".into(),
            git_ref: None,
            guest_ip: Some("192.0.2.2".into()),
            last_error: None,
            ssh: Some(SshAccess {
                user: "wt".into(),
                host: "192.0.2.2".into(),
                port: 22,
                host_keys: vec!["ssh-ed25519 AAAATEST guest".into()],
            }),
        };
        sync(&[instance]).unwrap();
        let managed = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        assert!(managed.contains("Host repo-feature-host\n"));
        assert!(managed.contains("Host repo-feature\n"));
        assert_eq!(managed.matches("RemoteCommand ").count(), 1);
        assert!(managed.contains("RemoteCommand /usr/local/bin/wt-app-shell"));
        assert_eq!(managed.matches("HostKeyAlias repo-feature").count(), 2);
        sync(&[]).unwrap();
        let main = fs::read_to_string(temp.path().join(".ssh/config")).unwrap();
        assert_eq!(main, main_config);
        let managed = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        assert!(!managed.contains("repo-feature"));
    }
}
