[package]
name = "wt-host"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "Raw Ubuntu host world lifecycle for wt"

[dependencies]
ssh-key = { workspace = true }
serde_yaml_ng = { workspace = true }
tempfile = "3.27.0"
wt-control-protocol = { workspace = true }
wt-libvirt-kvm = { workspace = true }
wt-retained-worlds = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
