use crate::config::atomic_write;
use crate::ProxyConfig;
use anyhow::{bail, Context, Result};
use ssh_key::{Algorithm, HashAlg, LineEnding, PrivateKey, PublicKey};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

const HEADER: &str = "# Generated by wt-git-proxy. Do not edit.\n";

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AuthorizedKey {
    pub fingerprint: String,
    pub label: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ClientBundle {
    pub alias: String,
    pub directory: PathBuf,
}

struct KeyEntry {
    key: PublicKey,
    label: String,
}

pub fn add_public_key(
    config_path: &Path,
    config: &ProxyConfig,
    label: &str,
    public_key: &str,
) -> Result<AuthorizedKey> {
    validate_label(label)?;
    let key = PublicKey::from_openssh(public_key).context("parse client public key")?;
    let key_fingerprint = fingerprint(&key);
    let mut entries = read_entries(&config.authorized_keys_file)?;
    if entries
        .iter()
        .any(|entry| fingerprint(&entry.key) == key_fingerprint)
    {
        bail!("client key {key_fingerprint} is already authorized");
    }
    entries.push(KeyEntry {
        key,
        label: label.to_owned(),
    });
    write_entries(config_path, config, &entries)?;
    Ok(AuthorizedKey {
        fingerprint: key_fingerprint,
        label: label.to_owned(),
    })
}

pub fn add_generated_key(
    config_path: &Path,
    config: &ProxyConfig,
    label: &str,
    output_directory: &Path,
) -> Result<(AuthorizedKey, ClientBundle)> {
    validate_label(label)?;
    if output_directory.exists() {
        bail!(
            "client bundle path already exists: {}",
            output_directory.display()
        );
    }
    let mut private = PrivateKey::random(&mut ssh_key::rand_core::OsRng, Algorithm::Ed25519)
        .context("generate client Ed25519 key")?;
    private.set_comment(format!("wt-git-proxy {label}"));
    let public = private
        .public_key()
        .to_openssh()
        .context("encode client public key")?;
    let public_key = PublicKey::from_openssh(&public).context("parse generated public key")?;
    let authorized = AuthorizedKey {
        fingerprint: fingerprint(&public_key),
        label: label.to_owned(),
    };
    let bundle = write_client_bundle(config, &authorized, &private, output_directory)?;
    let installed = add_public_key(config_path, config, label, &public)?;
    debug_assert_eq!(installed, authorized);
    Ok((authorized, bundle))
}

pub fn remove_key(
    config_path: &Path,
    config: &ProxyConfig,
    wanted_fingerprint: &str,
) -> Result<()> {
    let mut entries = read_entries(&config.authorized_keys_file)?;
    let original = entries.len();
    entries.retain(|entry| fingerprint(&entry.key) != wanted_fingerprint);
    if entries.len() == original {
        bail!("authorized client key not found: {wanted_fingerprint}");
    }
    write_entries(config_path, config, &entries)
}

pub fn list_keys(config: &ProxyConfig) -> Result<Vec<AuthorizedKey>> {
    Ok(read_entries(&config.authorized_keys_file)?
        .into_iter()
        .map(|entry| AuthorizedKey {
            fingerprint: fingerprint(&entry.key),
            label: entry.label,
        })
        .collect())
}

fn read_entries(path: &Path) -> Result<Vec<KeyEntry>> {
    let text = match fs::read_to_string(path) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(error) => {
            return Err(error).with_context(|| format!("read authorized keys {}", path.display()))
        }
    };
    text.lines()
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| {
            let (_, key) = line
                .split_once("\" ")
                .ok_or_else(|| anyhow::anyhow!("invalid managed authorized_keys entry"))?;
            let key = PublicKey::from_openssh(key).context("parse managed authorized key")?;
            let label = key.comment().to_owned();
            Ok(KeyEntry { key, label })
        })
        .collect()
}

fn write_entries(config_path: &Path, config: &ProxyConfig, entries: &[KeyEntry]) -> Result<()> {
    config.validate()?;
    let executable = safe_command_path("executable", &config.executable)?;
    let config_path = safe_command_path("config path", config_path)?;
    let command = format!("{executable} serve --config {config_path}");
    let mut output = HEADER.to_owned();
    for entry in entries {
        let encoded = entry.key.to_openssh().context("encode client public key")?;
        let mut fields = encoded.split_whitespace();
        let algorithm = fields.next().context("public key has no algorithm")?;
        let body = fields.next().context("public key has no body")?;
        output.push_str(&format!(
            "restrict,command=\"{command}\" {algorithm} {body} {}\n",
            entry.label
        ));
    }
    atomic_write(&config.authorized_keys_file, output.as_bytes(), 0o600)
}

fn write_client_bundle(
    config: &ProxyConfig,
    authorized: &AuthorizedKey,
    private: &PrivateKey,
    directory: &Path,
) -> Result<ClientBundle> {
    fs::create_dir(directory)
        .with_context(|| format!("create client bundle {}", directory.display()))?;
    fs::set_permissions(directory, fs::Permissions::from_mode(0o700))
        .with_context(|| format!("protect client bundle {}", directory.display()))?;

    let alias = format!(
        "wt-git-{}",
        authorized
            .fingerprint
            .chars()
            .filter(|character| character.is_ascii_alphanumeric())
            .take(12)
            .collect::<String>()
            .to_ascii_lowercase()
    );
    let install_directory = format!("~/.ssh/wt-git-proxy/{alias}");
    let private_key = private
        .to_openssh(LineEnding::LF)
        .context("encode client private key")?;
    write_file(&directory.join("id_ed25519"), private_key.as_bytes(), 0o600)?;

    let known_hosts = client_known_hosts(config)?;
    write_file(
        &directory.join("known_hosts"),
        known_hosts.as_bytes(),
        0o600,
    )?;
    let ssh_config = format!(
        "Host {alias}\n  HostName {}\n  Port {}\n  User {}\n  IdentityFile {install_directory}/id_ed25519\n  IdentitiesOnly yes\n  UserKnownHostsFile {install_directory}/known_hosts\n  StrictHostKeyChecking yes\n  PasswordAuthentication no\n  KbdInteractiveAuthentication no\n",
        config.client.host, config.client.port, config.client.user
    );
    write_file(&directory.join("config"), ssh_config.as_bytes(), 0o600)?;

    let repositories = config
        .repositories
        .iter()
        .map(|repository| format!("  git clone {alias}:{}\n", repository.path))
        .collect::<String>();
    let readme = format!(
        "Copy this directory to {install_directory} on the client.\nAdd this line to ~/.ssh/config:\n\n  Include ~/.ssh/wt-git-proxy/*/config\n\nConfigured repositories:\n{repositories}"
    );
    write_file(&directory.join("README"), readme.as_bytes(), 0o600)?;
    Ok(ClientBundle {
        alias,
        directory: directory.to_owned(),
    })
}

fn client_known_hosts(config: &ProxyConfig) -> Result<String> {
    let key = PublicKey::read_openssh_file(&config.client.host_key_file).with_context(|| {
        format!(
            "read client host key {}",
            config.client.host_key_file.display()
        )
    })?;
    let encoded = key.to_openssh().context("encode client host key")?;
    let mut fields = encoded.split_whitespace();
    let algorithm = fields.next().context("host key has no algorithm")?;
    let body = fields.next().context("host key has no body")?;
    let host = if config.client.port == 22 {
        config.client.host.clone()
    } else {
        format!("[{}]:{}", config.client.host, config.client.port)
    };
    Ok(format!("{host} {algorithm} {body}\n"))
}

fn write_file(path: &Path, bytes: &[u8], mode: u32) -> Result<()> {
    fs::write(path, bytes).with_context(|| format!("write {}", path.display()))?;
    fs::set_permissions(path, fs::Permissions::from_mode(mode))
        .with_context(|| format!("protect {}", path.display()))
}

fn safe_command_path<'a>(name: &str, path: &'a Path) -> Result<&'a str> {
    let value = path
        .to_str()
        .ok_or_else(|| anyhow::anyhow!("{name} must be UTF-8"))?;
    if !path.is_absolute()
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'/' | b'.' | b'_' | b'-'))
    {
        bail!("{name} contains characters unsafe for an OpenSSH forced command");
    }
    Ok(value)
}

fn validate_label(label: &str) -> Result<()> {
    if label.is_empty()
        || label.trim() != label
        || label.chars().any(|character| character.is_control())
    {
        bail!("client key label must be non-empty printable text");
    }
    Ok(())
}

fn fingerprint(key: &PublicKey) -> String {
    key.fingerprint(HashAlg::Sha256).to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{ClientConfig, RepositoryConfig, UpstreamConfig, CONFIG_VERSION};

    const PUBLIC_KEY: &str =
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPAo47CHM4yuzilWsuXWaYMSnEUMOCBQjSTLIofQSNqo test";

    fn config(root: &Path, host_key_file: PathBuf) -> ProxyConfig {
        ProxyConfig {
            version: CONFIG_VERSION,
            authorized_keys_file: root.join("authorized_keys"),
            executable: PathBuf::from("/usr/local/bin/wt-git-proxy"),
            client: ClientConfig {
                host: "proxy.example.test".to_owned(),
                port: 2222,
                user: "git-proxy".to_owned(),
                host_key_file,
            },
            write_prefix: "refs/heads/tasks/".to_owned(),
            allowed_branches: vec!["refs/heads/main".to_owned()],
            upstreams: vec![UpstreamConfig {
                name: "origin".to_owned(),
                host: "git.example.test".to_owned(),
                user: "git".to_owned(),
                port: None,
                private_key_file: root.join("upstream-key"),
                known_hosts_file: root.join("upstream-known-hosts"),
            }],
            repositories: vec![RepositoryConfig {
                path: "/team/project.git".to_owned(),
                upstream: "origin".to_owned(),
                upstream_path: "team/project.git".to_owned(),
            }],
        }
    }

    fn host_key(path: &Path) {
        let key = PrivateKey::random(&mut ssh_key::rand_core::OsRng, Algorithm::Ed25519).unwrap();
        fs::write(path, key.public_key().to_openssh().unwrap()).unwrap();
    }

    #[test]
    fn authorized_keys_is_the_only_client_access_state() {
        let temp = tempfile::tempdir().unwrap();
        let config_path = temp.path().join("config.toml");
        let host_key_file = temp.path().join("host.pub");
        host_key(&host_key_file);
        let config = config(temp.path(), host_key_file);

        let added = add_public_key(&config_path, &config, "cloud agent", PUBLIC_KEY).unwrap();
        assert_eq!(list_keys(&config).unwrap(), vec![added.clone()]);
        let text = fs::read_to_string(&config.authorized_keys_file).unwrap();
        let normalized = text.replace(temp.path().to_str().unwrap(), "[ROOT]");
        insta::assert_snapshot!(normalized, @r###"
        # Generated by wt-git-proxy. Do not edit.
        restrict,command="/usr/local/bin/wt-git-proxy serve --config [ROOT]/config.toml" ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPAo47CHM4yuzilWsuXWaYMSnEUMOCBQjSTLIofQSNqo cloud agent
        "###);
        remove_key(&config_path, &config, &added.fingerprint).unwrap();
        assert!(list_keys(&config).unwrap().is_empty());
        assert_eq!(
            fs::read_to_string(&config.authorized_keys_file).unwrap(),
            HEADER
        );
    }

    #[test]
    fn generated_bundle_contains_one_private_key_and_pinned_client_config() {
        let temp = tempfile::tempdir().unwrap();
        let config_path = temp.path().join("config.toml");
        let host_key_file = temp.path().join("host.pub");
        host_key(&host_key_file);
        let config = config(temp.path(), host_key_file);
        let output = temp.path().join("bundle");

        let (authorized, bundle) =
            add_generated_key(&config_path, &config, "cloud agent", &output).unwrap();
        assert_eq!(list_keys(&config).unwrap(), vec![authorized]);
        assert!(PrivateKey::read_openssh_file(&output.join("id_ed25519")).is_ok());
        assert_eq!(
            fs::metadata(output.join("id_ed25519"))
                .unwrap()
                .permissions()
                .mode()
                & 0o777,
            0o600
        );
        let combined = format!(
            "CONFIG\n{}KNOWN HOSTS\n{}README\n{}",
            fs::read_to_string(output.join("config")).unwrap(),
            fs::read_to_string(output.join("known_hosts")).unwrap(),
            fs::read_to_string(output.join("README")).unwrap(),
        )
        .replace(&bundle.alias, "[ALIAS]");
        let host_key = PublicKey::read_openssh_file(&config.client.host_key_file)
            .unwrap()
            .to_openssh()
            .unwrap();
        let host_key_body = host_key.split_whitespace().nth(1).unwrap();
        let combined = combined.replace(host_key_body, "[HOST KEY]");
        insta::assert_snapshot!(combined, @r###"
        CONFIG
        Host [ALIAS]
          HostName proxy.example.test
          Port 2222
          User git-proxy
          IdentityFile ~/.ssh/wt-git-proxy/[ALIAS]/id_ed25519
          IdentitiesOnly yes
          UserKnownHostsFile ~/.ssh/wt-git-proxy/[ALIAS]/known_hosts
          StrictHostKeyChecking yes
          PasswordAuthentication no
          KbdInteractiveAuthentication no
        KNOWN HOSTS
        [proxy.example.test]:2222 ssh-ed25519 [HOST KEY]
        README
        Copy this directory to ~/.ssh/wt-git-proxy/[ALIAS] on the client.
        Add this line to ~/.ssh/config:

          Include ~/.ssh/wt-git-proxy/*/config

        Configured repositories:
          git clone [ALIAS]:/team/project.git
        "###);
    }
}
