use crate::config::{atomic_write, authorized_keys_path};
use crate::ProxyConfig;
use anyhow::{bail, Context, Result};
use base64::prelude::{Engine as _, BASE64_STANDARD};
use ssh_key::{Algorithm, HashAlg, LineEnding, PrivateKey, PublicKey};
use std::fs;
use std::path::Path;

const HEADER: &str = "# Generated by wt-git-proxy. Do not edit.\n";

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AuthorizedKey {
    pub fingerprint: String,
    pub label: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedClient {
    pub fingerprint: String,
    pub alias: String,
    pub install_command: String,
}

pub fn add_public_key(
    config_path: &Path,
    executable: &Path,
    label: &str,
    public_key: &str,
) -> Result<AuthorizedKey> {
    validate_label(label)?;
    let mut key = PublicKey::from_openssh(public_key).context("parse client public key")?;
    key.set_comment(label);
    let key_fingerprint = fingerprint(&key);
    let mut entries = read_entries(config_path)?;
    if entries
        .iter()
        .any(|entry| fingerprint(entry) == key_fingerprint)
    {
        bail!("client key {key_fingerprint} is already authorized");
    }
    entries.push(key);
    write_entries(config_path, executable, &entries)?;
    Ok(AuthorizedKey {
        fingerprint: key_fingerprint,
        label: label.to_owned(),
    })
}

pub fn add_generated_client(
    config_path: &Path,
    executable: &Path,
    config: &ProxyConfig,
) -> Result<GeneratedClient> {
    let mut private = PrivateKey::random(&mut ssh_key::rand_core::OsRng, Algorithm::Ed25519)
        .context("generate client Ed25519 key")?;
    let key_fingerprint = fingerprint(private.public_key());
    let alias = client_alias(&key_fingerprint);
    private.set_comment(format!("wt-git-proxy {alias}"));
    let command = client_install_command(&alias, &private, config)?;
    let public = private
        .public_key()
        .to_openssh()
        .context("encode client public key")?;
    let authorized = add_public_key(config_path, executable, &alias, &public)?;
    Ok(GeneratedClient {
        fingerprint: authorized.fingerprint,
        alias,
        install_command: command,
    })
}

pub fn remove_key(config_path: &Path, executable: &Path, wanted: &str) -> Result<()> {
    let mut entries = read_entries(config_path)?;
    let original = entries.len();
    entries.retain(|entry| fingerprint(entry) != wanted);
    if entries.len() == original {
        bail!("authorized client key not found: {wanted}");
    }
    write_entries(config_path, executable, &entries)
}

pub fn list_keys(config_path: &Path) -> Result<Vec<AuthorizedKey>> {
    Ok(read_entries(config_path)?
        .into_iter()
        .map(|key| AuthorizedKey {
            fingerprint: fingerprint(&key),
            label: key.comment().to_owned(),
        })
        .collect())
}

fn read_entries(config_path: &Path) -> Result<Vec<PublicKey>> {
    let path = authorized_keys_path(config_path);
    let text = match fs::read_to_string(&path) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(error) => return Err(error).with_context(|| format!("read {}", path.display())),
    };
    text.lines()
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| {
            let (_, key) = line
                .split_once("\" ")
                .context("invalid managed authorized_keys entry")?;
            PublicKey::from_openssh(key).context("parse managed authorized key")
        })
        .collect()
}

fn write_entries(config_path: &Path, executable: &Path, entries: &[PublicKey]) -> Result<()> {
    let executable = safe_command_path("executable", executable)?;
    let config_path_text = safe_command_path("config path", config_path)?;
    let command = format!("{executable} serve --config {config_path_text}");
    let mut output = HEADER.to_owned();
    for key in entries {
        let key = key.to_openssh().context("encode client public key")?;
        output.push_str(&format!("restrict,command=\"{command}\" {key}\n"));
    }
    atomic_write(&authorized_keys_path(config_path), output.as_bytes(), 0o600)
}

fn client_install_command(
    alias: &str,
    private: &PrivateKey,
    config: &ProxyConfig,
) -> Result<String> {
    let hostname = proxy_hostname()?;
    let host_key = PublicKey::read_openssh_file(Path::new("/etc/ssh/ssh_host_ed25519_key.pub"))?;
    let encoded = host_key.to_openssh()?;
    let mut fields = encoded.split_whitespace();
    let algorithm = fields
        .next()
        .context("proxy host public key has no algorithm")?;
    let key = fields.next().context("proxy host public key has no key")?;
    let known_hosts = format!("{hostname} {algorithm} {key}\n");
    let private = private.to_openssh(LineEnding::LF)?;
    Ok(render_install_command(
        alias,
        &hostname,
        private.as_bytes(),
        known_hosts.as_bytes(),
        config
            .providers
            .iter()
            .map(|provider| provider.host.as_str()),
    ))
}

pub(crate) fn proxy_hostname() -> Result<String> {
    let output = std::process::Command::new("hostname")
        .arg("--fqdn")
        .output()
        .context("find proxy hostname")?;
    if !output.status.success() {
        bail!("hostname --fqdn failed");
    }
    let hostname = String::from_utf8(output.stdout)
        .context("proxy hostname is not UTF-8")?
        .trim()
        .to_owned();
    if hostname.is_empty() || hostname.chars().any(char::is_whitespace) {
        bail!("hostname --fqdn returned an invalid hostname");
    }
    Ok(hostname)
}

fn client_alias(fingerprint: &str) -> String {
    let suffix = fingerprint
        .strip_prefix("SHA256:")
        .unwrap_or(fingerprint)
        .chars()
        .filter(char::is_ascii_alphanumeric)
        .take(12)
        .collect::<String>()
        .to_ascii_lowercase();
    format!("wt-git-{suffix}")
}

fn render_install_command<'a>(
    alias: &str,
    hostname: &str,
    private_key: &[u8],
    known_hosts: &[u8],
    providers: impl Iterator<Item = &'a str>,
) -> String {
    let install_directory = format!("~/.ssh/wt-git-proxy/{alias}");
    let ssh_config = format!(
        "Host {alias}\n  HostName {hostname}\n  User git-proxy\n  IdentityFile {install_directory}/id_ed25519\n  IdentitiesOnly yes\n  UserKnownHostsFile {install_directory}/known_hosts\n  StrictHostKeyChecking yes\n  PasswordAuthentication no\n"
    );
    let mut git_config = String::new();
    for provider in providers {
        git_config.push_str(&format!(
            "[url \"{alias}:{provider}/\"]\n  insteadOf = https://{provider}/\n  insteadOf = git@{provider}:\n  insteadOf = ssh://git@{provider}/\n"
        ));
    }
    format!(
        "umask 077; d=\"$HOME/.ssh/wt-git-proxy/{alias}\"; g=\"$HOME/.ssh/wt-git-proxy/gitconfig\"; install -d \"$d\"; printf '%s' '{}' | base64 -d > \"$d/id_ed25519\"; printf '%s' '{}' | base64 -d > \"$d/known_hosts\"; printf '%s' '{}' | base64 -d > \"$d/config\"; printf '%s' '{}' | base64 -d > \"$g\"; touch \"$HOME/.ssh/config\"; chmod 600 \"$HOME/.ssh/config\"; grep -qxF 'Include ~/.ssh/wt-git-proxy/*/config' \"$HOME/.ssh/config\" || printf '\\nInclude ~/.ssh/wt-git-proxy/*/config\\n' >> \"$HOME/.ssh/config\"; git config --global --get-all include.path 2>/dev/null | grep -qxF \"$g\" || git config --global --add include.path \"$g\"",
        BASE64_STANDARD.encode(private_key),
        BASE64_STANDARD.encode(known_hosts),
        BASE64_STANDARD.encode(ssh_config),
        BASE64_STANDARD.encode(git_config),
    )
}

fn safe_command_path<'a>(name: &str, path: &'a Path) -> Result<&'a str> {
    let value = path.to_str().context("path must be UTF-8")?;
    if !path.is_absolute()
        || !value
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'/' | b'.' | b'_' | b'-'))
    {
        bail!("{name} contains characters unsafe for a forced command");
    }
    Ok(value)
}

fn validate_label(label: &str) -> Result<()> {
    if label.is_empty() || label.trim() != label || label.chars().any(char::is_control) {
        bail!("client key label must be non-empty printable text");
    }
    Ok(())
}

fn fingerprint(key: &PublicKey) -> String {
    key.fingerprint(HashAlg::Sha256).to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;

    #[test]
    fn generated_command_is_complete_and_copyable() {
        let command = render_install_command(
            "wt-git-abc123",
            "proxy.example.com",
            b"PRIVATE KEY\n",
            b"proxy.example.com ssh-ed25519 HOSTKEY\n",
            ["github.com"].into_iter(),
        );
        insta::assert_snapshot!(command);
    }

    #[test]
    fn generated_command_configures_an_existing_checkout_globally() {
        let home = tempfile::tempdir().unwrap();
        let command = render_install_command(
            "wt-git-abc123",
            "proxy.example.com",
            b"PRIVATE KEY\n",
            b"proxy.example.com ssh-ed25519 HOSTKEY\n",
            ["github.com"].into_iter(),
        );
        for _ in 0..2 {
            let status = Command::new("/bin/sh")
                .arg("-c")
                .arg(&command)
                .env("HOME", home.path())
                .status()
                .unwrap();
            assert!(status.success());
        }
        let replacement = render_install_command(
            "wt-git-def456",
            "proxy.example.com",
            b"REPLACEMENT KEY\n",
            b"proxy.example.com ssh-ed25519 HOSTKEY\n",
            ["github.com"].into_iter(),
        );
        assert!(Command::new("/bin/sh")
            .arg("-c")
            .arg(replacement)
            .env("HOME", home.path())
            .status()
            .unwrap()
            .success());
        let directory = home.path().join(".ssh/wt-git-proxy/wt-git-abc123");
        assert_eq!(
            fs::read(directory.join("id_ed25519")).unwrap(),
            b"PRIVATE KEY\n"
        );
        let ssh_config = fs::read_to_string(home.path().join(".ssh/config")).unwrap();
        assert_eq!(
            ssh_config
                .matches("Include ~/.ssh/wt-git-proxy/*/config")
                .count(),
            1
        );
        let git_config =
            fs::read_to_string(home.path().join(".ssh/wt-git-proxy/gitconfig")).unwrap();
        assert!(git_config.contains("insteadOf = https://github.com/"));
        let checkout = home.path().join("checkout");
        assert!(Command::new("git")
            .args(["init", "--quiet"])
            .arg(&checkout)
            .env("HOME", home.path())
            .status()
            .unwrap()
            .success());
        assert!(Command::new("git")
            .args(["-C"])
            .arg(&checkout)
            .args([
                "remote",
                "add",
                "origin",
                "https://github.com/team/project.git",
            ])
            .env("HOME", home.path())
            .status()
            .unwrap()
            .success());
        let rewritten = Command::new("git")
            .args(["-C"])
            .arg(&checkout)
            .args(["remote", "get-url", "origin"])
            .env("HOME", home.path())
            .output()
            .unwrap();
        assert_eq!(
            String::from_utf8(rewritten.stdout).unwrap().trim(),
            "wt-git-def456:github.com/team/project.git"
        );
        let includes = Command::new("git")
            .args(["config", "--global", "--get-all", "include.path"])
            .env("HOME", home.path())
            .output()
            .unwrap();
        assert_eq!(
            String::from_utf8(includes.stdout).unwrap().lines().count(),
            1
        );
    }

    #[test]
    fn aliases_use_fingerprint_entropy() {
        assert_eq!(client_alias("SHA256:AbC+/123xyz987"), "wt-git-abc123xyz987");
    }
}
