use crate::config::{atomic_write, authorized_keys_path};
use crate::ClientConfig;
use anyhow::{bail, Context, Result};
use ssh_key::{Algorithm, HashAlg, LineEnding, PrivateKey, PublicKey};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

const HEADER: &str = "# Generated by wt-git-proxy. Do not edit.\n";

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AuthorizedKey {
    pub fingerprint: String,
    pub label: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ClientBundle {
    pub alias: String,
    pub directory: PathBuf,
}

struct KeyEntry {
    key: PublicKey,
    label: String,
}

pub fn add_public_key(
    config_path: &Path,
    executable: &Path,
    label: &str,
    public_key: &str,
) -> Result<AuthorizedKey> {
    validate_label(label)?;
    let key = PublicKey::from_openssh(public_key).context("parse client public key")?;
    let key_fingerprint = fingerprint(&key);
    let mut entries = read_entries(config_path)?;
    if entries
        .iter()
        .any(|entry| fingerprint(&entry.key) == key_fingerprint)
    {
        bail!("client key {key_fingerprint} is already authorized");
    }
    entries.push(KeyEntry {
        key,
        label: label.to_owned(),
    });
    write_entries(config_path, executable, &entries)?;
    Ok(AuthorizedKey {
        fingerprint: key_fingerprint,
        label: label.to_owned(),
    })
}

pub fn add_generated_key(
    config_path: &Path,
    executable: &Path,
    client: &ClientConfig,
    label: &str,
    output_directory: &Path,
) -> Result<(AuthorizedKey, ClientBundle)> {
    let mut private = PrivateKey::random(&mut ssh_key::rand_core::OsRng, Algorithm::Ed25519)
        .context("generate client Ed25519 key")?;
    private.set_comment(format!("wt-git-proxy {label}"));
    let public = private
        .public_key()
        .to_openssh()
        .context("encode client public key")?;
    let key = PublicKey::from_openssh(&public).context("parse generated public key")?;
    let authorized = AuthorizedKey {
        fingerprint: fingerprint(&key),
        label: label.to_owned(),
    };
    let bundle = write_client_bundle(client, &authorized, &private, output_directory)?;
    let installed = add_public_key(config_path, executable, label, &public)?;
    debug_assert_eq!(installed, authorized);
    Ok((authorized, bundle))
}

pub fn remove_key(config_path: &Path, executable: &Path, wanted: &str) -> Result<()> {
    let mut entries = read_entries(config_path)?;
    let original = entries.len();
    entries.retain(|entry| fingerprint(&entry.key) != wanted);
    if entries.len() == original {
        bail!("authorized client key not found: {wanted}");
    }
    write_entries(config_path, executable, &entries)
}

pub fn list_keys(config_path: &Path) -> Result<Vec<AuthorizedKey>> {
    Ok(read_entries(config_path)?
        .into_iter()
        .map(|entry| AuthorizedKey {
            fingerprint: fingerprint(&entry.key),
            label: entry.label,
        })
        .collect())
}

fn read_entries(config_path: &Path) -> Result<Vec<KeyEntry>> {
    let path = authorized_keys_path(config_path);
    let text = match fs::read_to_string(&path) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(error) => return Err(error).with_context(|| format!("read {}", path.display())),
    };
    text.lines()
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| {
            let (_, key) = line
                .split_once("\" ")
                .context("invalid managed authorized_keys entry")?;
            let key = PublicKey::from_openssh(key).context("parse managed authorized key")?;
            Ok(KeyEntry {
                label: key.comment().to_owned(),
                key,
            })
        })
        .collect()
}

fn write_entries(config_path: &Path, executable: &Path, entries: &[KeyEntry]) -> Result<()> {
    let executable = safe_command_path("executable", executable)?;
    let config_path_text = safe_command_path("config path", config_path)?;
    let command = format!("{executable} serve --config {config_path_text}");
    let mut output = HEADER.to_owned();
    for entry in entries {
        let encoded = entry.key.to_openssh().context("encode client public key")?;
        let mut fields = encoded.split_whitespace();
        output.push_str(&format!(
            "restrict,command=\"{command}\" {} {} {}\n",
            fields.next().context("public key has no algorithm")?,
            fields.next().context("public key has no body")?,
            entry.label
        ));
    }
    atomic_write(&authorized_keys_path(config_path), output.as_bytes(), 0o600)
}

fn write_client_bundle(
    client: &ClientConfig,
    authorized: &AuthorizedKey,
    private: &PrivateKey,
    directory: &Path,
) -> Result<ClientBundle> {
    if directory.exists() {
        bail!("client bundle path already exists: {}", directory.display());
    }
    fs::create_dir(directory).with_context(|| format!("create {}", directory.display()))?;
    fs::set_permissions(directory, fs::Permissions::from_mode(0o700))?;
    let alias = format!(
        "wt-git-{}",
        authorized
            .fingerprint
            .chars()
            .filter(|c| c.is_ascii_alphanumeric())
            .take(12)
            .collect::<String>()
            .to_ascii_lowercase()
    );
    let install_directory = format!("~/.ssh/wt-git-proxy/{alias}");
    write_file(
        &directory.join("id_ed25519"),
        private.to_openssh(LineEnding::LF)?.as_bytes(),
    )?;
    let host_key = PublicKey::read_openssh_file(&client.host_key_file)?;
    let encoded = host_key.to_openssh()?;
    let mut fields = encoded.split_whitespace();
    let host = if client.port == 22 {
        client.host.clone()
    } else {
        format!("[{}]:{}", client.host, client.port)
    };
    write_file(
        &directory.join("known_hosts"),
        format!(
            "{host} {} {}\n",
            fields.next().unwrap(),
            fields.next().unwrap()
        )
        .as_bytes(),
    )?;
    write_file(&directory.join("config"), format!("Host {alias}\n  HostName {}\n  Port {}\n  User {}\n  IdentityFile {install_directory}/id_ed25519\n  IdentitiesOnly yes\n  UserKnownHostsFile {install_directory}/known_hosts\n  StrictHostKeyChecking yes\n  PasswordAuthentication no\n", client.host, client.port, client.user).as_bytes())?;
    write_file(&directory.join("README"), format!("Copy this directory to {install_directory}.\nAdd `Include ~/.ssh/wt-git-proxy/*/config` to ~/.ssh/config.\nClone with: git clone {alias}:OWNER/REPOSITORY.git\n").as_bytes())?;
    Ok(ClientBundle {
        alias,
        directory: directory.to_owned(),
    })
}

fn write_file(path: &Path, bytes: &[u8]) -> Result<()> {
    fs::write(path, bytes)?;
    fs::set_permissions(path, fs::Permissions::from_mode(0o600))?;
    Ok(())
}

fn safe_command_path<'a>(name: &str, path: &'a Path) -> Result<&'a str> {
    let value = path.to_str().context("path must be UTF-8")?;
    if !path.is_absolute()
        || !value
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'/' | b'.' | b'_' | b'-'))
    {
        bail!("{name} contains characters unsafe for a forced command");
    }
    Ok(value)
}

fn validate_label(label: &str) -> Result<()> {
    if label.is_empty() || label.trim() != label || label.chars().any(char::is_control) {
        bail!("client key label must be non-empty printable text");
    }
    Ok(())
}

fn fingerprint(key: &PublicKey) -> String {
    key.fingerprint(HashAlg::Sha256).to_string()
}
