use crate::atomic_file;
use crate::config::{validate_ssh_host, ClientConfig, ContextKind};
use crate::inventory::{name_counts, ContextWorld};
use crate::ssh_config;
use anyhow::{bail, Context, Result};
use nix::fcntl::{Flock, FlockArg};
use std::fs::{self, OpenOptions};
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};
use wt_control_protocol::WorldStatus;

pub fn sync(client_config: &ClientConfig, worlds: &[ContextWorld]) -> Result<PathBuf> {
    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .context("HOME is not set")?;
    sync_in_home(&home, client_config, worlds)
}

fn sync_in_home(
    home: &Path,
    client_config: &ClientConfig,
    worlds: &[ContextWorld],
) -> Result<PathBuf> {
    let ssh_dir = home.join(".ssh");
    let managed_dir = ssh_dir.join("wt");
    ensure_directory(&ssh_dir)?;
    ensure_directory(&managed_dir)?;
    let lock_path = managed_dir.join("inventory.lock");
    let lock_file = OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(false)
        .mode(0o600)
        .open(&lock_path)
        .with_context(|| format!("open {}", lock_path.display()))?;
    let _lock = Flock::lock(lock_file, FlockArg::LockExclusive)
        .map_err(|(_, error)| error)
        .with_context(|| format!("lock {}", lock_path.display()))?;
    let config_path = managed_dir.join("config");
    let known_hosts_path = managed_dir.join("known_hosts");
    let main_config_path = ssh_dir.join("config");

    let accessible = worlds.iter().filter(|item| has_alias(item));
    let counts = name_counts(worlds);
    let mut config = String::from("# Generated by wt sync. Do not edit.\n");
    let mut known_hosts = String::from("# Generated by wt sync. Do not edit.\n");
    for item in accessible {
        let world = &item.world;
        let ssh = world.ssh.as_ref().expect("filtered SSH access");
        if ssh.host_keys.is_empty() {
            bail!("world {} has incomplete SSH host keys", world.name);
        }
        let qualified = item.qualified_name();
        let context = client_config
            .context(&item.context)
            .with_context(|| format!("missing client context {}", item.context))?;
        let (proxy_jump, compression) = match &context.kind {
            ContextKind::BareMetalLocal => (String::new(), "no"),
            ContextKind::BareMetalSsh { host } => {
                validate_ssh_host(&context.name, host)?;
                (format!("  ProxyJump {host}\n"), "yes")
            }
        };
        let known_hosts_file = ssh_quote(&known_hosts_path);
        let unique_name = counts.get(world.name.as_str()) == Some(&1);
        let guest_shell = format!("BYOBU_ALT_TITLE='{qualified}' /usr/local/bin/wt-guest-shell");
        let guest_common =
            guest_options(ssh, &qualified, &known_hosts_file, compression, &proxy_jump);
        config.push_str(&format!(
            "\nHost {qualified}\n{guest_common}  RequestTTY force\n  RemoteCommand {guest_shell}\n\nHost {qualified}-direct\n{guest_common}"
        ));
        if unique_name {
            config.push_str(&format!(
                "\nHost {}\n{guest_common}  RequestTTY force\n  RemoteCommand {guest_shell}\n\nHost {}-direct\n{guest_common}",
                world.name, world.name
            ));
        }
        for key in &ssh.host_keys {
            append_known_host(&mut known_hosts, &qualified, key, world)?;
        }
    }
    ssh_config::ensure_managed_include(&main_config_path).with_context(|| {
        format!(
            "configure WT SSH aliases in {}\nadd `Include ~/.ssh/wt/config` outside any `Host` or `Match` block, then run `wt sync`",
            main_config_path.display()
        )
    })?;
    atomic_file::replace(&config_path, config.as_bytes())?;
    atomic_file::replace(&known_hosts_path, known_hosts.as_bytes())?;
    Ok(config_path)
}

pub fn has_alias(item: &ContextWorld) -> bool {
    matches!(item.world.status, WorldStatus::Running | WorldStatus::Error)
        && item.world.ssh.is_some()
}

fn guest_options(
    ssh: &wt_control_protocol::SshAccess,
    host_key_alias: &str,
    known_hosts_file: &str,
    compression: &str,
    proxy_jump: &str,
) -> String {
    format!(
        "  HostName {}\n  User {}\n  Port {}\n  HostKeyAlias {host_key_alias}\n  UserKnownHostsFile {known_hosts_file}\n  StrictHostKeyChecking yes\n  Compression {compression}\n  ServerAliveInterval 30\n  ServerAliveCountMax 3\n  PasswordAuthentication no\n  KbdInteractiveAuthentication no\n{proxy_jump}",
        ssh.host, ssh.user, ssh.port,
    )
}

fn append_known_host(
    known_hosts: &mut String,
    alias: &str,
    key: &str,
    world: &wt_control_protocol::World,
) -> Result<()> {
    let mut fields = key.split_whitespace();
    let kind = fields.next().unwrap_or_default();
    let data = fields.next().unwrap_or_default();
    if kind.is_empty() || data.is_empty() {
        bail!("world {} has an invalid SSH host key", world.name);
    }
    known_hosts.push_str(&format!("{alias} {kind} {data}\n"));
    Ok(())
}

fn ensure_directory(path: &Path) -> Result<()> {
    fs::create_dir_all(path).with_context(|| format!("create {}", path.display()))?;
    fs::set_permissions(path, fs::Permissions::from_mode(0o700))
        .with_context(|| format!("set permissions on {}", path.display()))
}

fn ssh_quote(path: &Path) -> String {
    format!(
        "\"{}\"",
        path.display()
            .to_string()
            .replace('\\', "\\\\")
            .replace('\"', "\\\"")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Context as ClientContext, ContextKind};
    use std::sync::Mutex;
    use uuid::Uuid;
    use wt_control_protocol::{SshAccess, World, WorldName};

    static HOME_LOCK: Mutex<()> = Mutex::new(());

    fn local_config() -> ClientConfig {
        ClientConfig {
            contexts: vec![ClientContext {
                name: "local".into(),
                kind: ContextKind::BareMetalLocal,
            }],
        }
    }

    fn normalize_home(contents: &str, home: &Path) -> String {
        contents.replace(&home.display().to_string(), "[HOME]")
    }

    fn world(name: &str, host_key: &str) -> ContextWorld {
        ContextWorld {
            context: "local".into(),
            world_mail_count: 0,
            disk_usage_bytes: None,
            world: World {
                world_id: Uuid::new_v4().into(),
                name: WorldName::parse(name).unwrap(),
                owner: "lucas".into(),
                status: WorldStatus::Running,
                vcpus: 2,
                memory_mib: 4096,
                disk_gib: 32,
                guest_ip: Some("192.0.2.2".into()),
                last_error: None,
                ssh: Some(SshAccess {
                    user: "wt".into(),
                    host: "192.0.2.2".into(),
                    port: 22,
                    host_keys: vec![format!("ssh-ed25519 {host_key} guest")],
                }),
            },
        }
    }

    #[test]
    fn concurrent_syncs_publish_one_inventory_generation() {
        let temp = tempfile::tempdir().unwrap();
        let config = local_config();
        let inventories = (0..16)
            .map(|index| vec![world(&format!("world-{index}"), &format!("KEY{index}"))])
            .collect::<Vec<_>>();
        let barrier = std::sync::Barrier::new(inventories.len());

        std::thread::scope(|scope| {
            let threads = inventories
                .iter()
                .map(|inventory| {
                    scope.spawn(|| {
                        barrier.wait();
                        sync_in_home(temp.path(), &config, inventory)
                    })
                })
                .collect::<Vec<_>>();
            for thread in threads {
                thread.join().unwrap().unwrap();
            }
        });

        let managed_dir = temp.path().join(".ssh/wt");
        let published_config = fs::read_to_string(managed_dir.join("config")).unwrap();
        let published_known_hosts = fs::read_to_string(managed_dir.join("known_hosts")).unwrap();
        assert!((0..inventories.len()).any(|generation| {
            published_config.contains(&format!("\nHost local.world-{generation}\n"))
                && published_known_hosts.contains(&format!(
                    "\nlocal.world-{generation} ssh-ed25519 KEY{generation}\n"
                ))
        }));
        assert_eq!(
            fs::metadata(managed_dir.join("inventory.lock"))
                .unwrap()
                .permissions()
                .mode()
                & 0o777,
            0o600
        );
    }

    #[test]
    fn sync_bootstraps_main_config_and_removes_stale_worlds() {
        let _lock = HOME_LOCK.lock().unwrap();
        let temp = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", temp.path());
        fs::create_dir(temp.path().join(".ssh")).unwrap();
        let main_config = "Include ~/.ssh/wt/config\nHost personal\n  HostName example.test\n";
        fs::write(temp.path().join(".ssh/config"), main_config).unwrap();
        let world = World {
            world_id: Uuid::new_v4().into(),
            name: WorldName::parse("repo-feature").unwrap(),
            owner: "lucas".into(),
            status: WorldStatus::Running,
            vcpus: 2,
            memory_mib: 4096,
            disk_gib: 32,
            guest_ip: Some("192.0.2.2".into()),
            last_error: None,
            ssh: Some(SshAccess {
                user: "wt".into(),
                host: "192.0.2.2".into(),
                port: 22,
                host_keys: vec!["ssh-ed25519 AAAATEST guest".into()],
            }),
        };
        let mut replacement_world = world.clone();
        replacement_world.world_id = Uuid::new_v4().into();
        replacement_world.ssh.as_mut().unwrap().host_keys =
            vec!["ssh-ed25519 AAAAREPLACEMENT guest".into()];
        let client_config = local_config();
        sync(
            &client_config,
            &[ContextWorld {
                context: "local".into(),
                world_mail_count: 0,
                disk_usage_bytes: None,
                world,
            }],
        )
        .unwrap();
        let managed = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        insta::assert_snapshot!(
            "unique_world_ssh_config",
            normalize_home(&managed, temp.path())
        );
        sync(
            &client_config,
            &[ContextWorld {
                context: "local".into(),
                world_mail_count: 0,
                disk_usage_bytes: None,
                world: replacement_world,
            }],
        )
        .unwrap();
        let known_hosts = fs::read_to_string(temp.path().join(".ssh/wt/known_hosts")).unwrap();
        insta::assert_snapshot!(known_hosts, @r###"
        # Generated by wt sync. Do not edit.
        local.repo-feature ssh-ed25519 AAAAREPLACEMENT
        "###);
        sync(&client_config, &[]).unwrap();
        let main = fs::read_to_string(temp.path().join(".ssh/config")).unwrap();
        assert_eq!(main, main_config);
        let managed = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        assert!(!managed.contains("repo-feature"));
    }

    #[test]
    fn running_world_has_host_aliases_without_agent_forwarding() {
        let _lock = HOME_LOCK.lock().unwrap();
        let temp = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", temp.path());
        let world = World {
            world_id: Uuid::new_v4().into(),
            name: WorldName::parse("repo-feature").unwrap(),
            owner: "lucas".into(),
            status: WorldStatus::Running,
            vcpus: 2,
            memory_mib: 4096,
            disk_gib: 32,
            guest_ip: Some("192.0.2.2".into()),
            last_error: None,
            ssh: Some(SshAccess {
                user: "wt".into(),
                host: "192.0.2.2".into(),
                port: 22,
                host_keys: vec!["ssh-ed25519 AAAATEST guest".into()],
            }),
        };
        sync(
            &local_config(),
            &[ContextWorld {
                context: "local".into(),
                world_mail_count: 0,
                disk_usage_bytes: None,
                world,
            }],
        )
        .unwrap();
        let managed = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        insta::assert_snapshot!(
            "running_world_ssh_config",
            normalize_home(&managed, temp.path())
        );
        let known_hosts = fs::read_to_string(temp.path().join(".ssh/wt/known_hosts")).unwrap();
        insta::assert_snapshot!("running_world_known_hosts", known_hosts);
    }

    #[test]
    fn host_world_has_byobu_and_direct_ssh_aliases() {
        let _lock = HOME_LOCK.lock().unwrap();
        let temp = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", temp.path());
        let world = World {
            world_id: Uuid::new_v4().into(),
            name: WorldName::parse("ubuntu").unwrap(),
            owner: "lucas".into(),
            status: WorldStatus::Running,
            vcpus: 2,
            memory_mib: 4096,
            disk_gib: 32,
            guest_ip: Some("192.0.2.3".into()),
            last_error: None,
            ssh: Some(SshAccess {
                user: "wt".into(),
                host: "192.0.2.3".into(),
                port: 22,
                host_keys: vec!["ssh-ed25519 AAAAHOST host".into()],
            }),
        };
        sync(
            &local_config(),
            &[ContextWorld {
                context: "local".into(),
                world_mail_count: 0,
                disk_usage_bytes: None,
                world,
            }],
        )
        .unwrap();
        let config = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        let known_hosts = fs::read_to_string(temp.path().join(".ssh/wt/known_hosts")).unwrap();
        insta::assert_snapshot!(normalize_home(&config, temp.path()), @r###"
        # Generated by wt sync. Do not edit.

        Host local.ubuntu
          HostName 192.0.2.3
          User wt
          Port 22
          HostKeyAlias local.ubuntu
          UserKnownHostsFile "[HOME]/.ssh/wt/known_hosts"
          StrictHostKeyChecking yes
          Compression no
          ServerAliveInterval 30
          ServerAliveCountMax 3
          PasswordAuthentication no
          KbdInteractiveAuthentication no
          RequestTTY force
          RemoteCommand BYOBU_ALT_TITLE='local.ubuntu' /usr/local/bin/wt-guest-shell

        Host local.ubuntu-direct
          HostName 192.0.2.3
          User wt
          Port 22
          HostKeyAlias local.ubuntu
          UserKnownHostsFile "[HOME]/.ssh/wt/known_hosts"
          StrictHostKeyChecking yes
          Compression no
          ServerAliveInterval 30
          ServerAliveCountMax 3
          PasswordAuthentication no
          KbdInteractiveAuthentication no

        Host ubuntu
          HostName 192.0.2.3
          User wt
          Port 22
          HostKeyAlias local.ubuntu
          UserKnownHostsFile "[HOME]/.ssh/wt/known_hosts"
          StrictHostKeyChecking yes
          Compression no
          ServerAliveInterval 30
          ServerAliveCountMax 3
          PasswordAuthentication no
          KbdInteractiveAuthentication no
          RequestTTY force
          RemoteCommand BYOBU_ALT_TITLE='local.ubuntu' /usr/local/bin/wt-guest-shell

        Host ubuntu-direct
          HostName 192.0.2.3
          User wt
          Port 22
          HostKeyAlias local.ubuntu
          UserKnownHostsFile "[HOME]/.ssh/wt/known_hosts"
          StrictHostKeyChecking yes
          Compression no
          ServerAliveInterval 30
          ServerAliveCountMax 3
          PasswordAuthentication no
          KbdInteractiveAuthentication no
        "###);
        insta::assert_snapshot!(known_hosts, @r###"
        # Generated by wt sync. Do not edit.
        local.ubuntu ssh-ed25519 AAAAHOST
        "###);
    }

    #[test]
    fn failed_host_keeps_recovery_aliases() {
        let _lock = HOME_LOCK.lock().unwrap();
        let temp = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", temp.path());
        let world = World {
            world_id: Uuid::new_v4().into(),
            name: WorldName::parse("broken").unwrap(),
            owner: "lucas".into(),
            status: WorldStatus::Error,
            vcpus: 2,
            memory_mib: 4096,
            disk_gib: 32,
            guest_ip: Some("192.0.2.4".into()),
            last_error: Some("host preparation failed".into()),
            ssh: Some(SshAccess {
                user: "wt".into(),
                host: "192.0.2.4".into(),
                port: 22,
                host_keys: vec!["ssh-ed25519 AAAAHOST host".into()],
            }),
        };

        sync(
            &local_config(),
            &[ContextWorld {
                context: "local".into(),
                world_mail_count: 0,
                disk_usage_bytes: None,
                world,
            }],
        )
        .unwrap();

        let config = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        assert!(config.contains("Host local.broken\n"));
        assert!(config.contains("Host local.broken-direct\n"));
    }

    #[test]
    fn duplicate_names_only_receive_qualified_aliases() {
        let _lock = HOME_LOCK.lock().unwrap();
        let temp = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", temp.path());
        let world = |id: Uuid, context: &str| ContextWorld {
            context: context.into(),
            world_mail_count: 0,
            disk_usage_bytes: None,
            world: World {
                world_id: id.into(),
                name: WorldName::parse("same").unwrap(),
                owner: "lucas".into(),
                status: WorldStatus::Running,
                vcpus: 2,
                memory_mib: 4096,
                disk_gib: 32,
                guest_ip: Some("192.0.2.2".into()),
                last_error: None,
                ssh: Some(SshAccess {
                    user: "wt".into(),
                    host: "192.0.2.2".into(),
                    port: 22,
                    host_keys: vec!["ssh-ed25519 AAAATEST guest".into()],
                }),
            },
        };
        let client_config = ClientConfig {
            contexts: vec![
                ClientContext {
                    name: "local".into(),
                    kind: ContextKind::BareMetalLocal,
                },
                ClientContext {
                    name: "lab".into(),
                    kind: ContextKind::BareMetalSsh {
                        host: "wt-server".into(),
                    },
                },
            ],
        };
        sync(
            &client_config,
            &[world(Uuid::new_v4(), "local"), world(Uuid::new_v4(), "lab")],
        )
        .unwrap();
        let managed = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        insta::assert_snapshot!(
            "duplicate_world_names_ssh_config",
            normalize_home(&managed, temp.path())
        );
        assert_eq!(
            fs::read_to_string(temp.path().join(".ssh/config")).unwrap(),
            "Include ~/.ssh/wt/config\n"
        );
    }

    #[test]
    fn remote_world_aliases_jump_through_the_context_host() {
        let _lock = HOME_LOCK.lock().unwrap();
        let temp = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", temp.path());
        let world = |name: &str, host: &str| ContextWorld {
            context: "lab".into(),
            world_mail_count: 0,
            disk_usage_bytes: None,
            world: World {
                world_id: Uuid::new_v4().into(),
                name: WorldName::parse(name).unwrap(),
                owner: "lucas".into(),
                status: WorldStatus::Running,
                vcpus: 2,
                memory_mib: 4096,
                disk_gib: 32,
                guest_ip: Some(host.into()),
                last_error: None,
                ssh: Some(SshAccess {
                    user: "wt".into(),
                    host: host.into(),
                    port: 22,
                    host_keys: vec!["ssh-ed25519 AAAATEST guest".into()],
                }),
            },
        };
        let client_config = ClientConfig {
            contexts: vec![ClientContext {
                name: "lab".into(),
                kind: ContextKind::BareMetalSsh {
                    host: "wt-server".into(),
                },
            }],
        };

        sync(
            &client_config,
            &[
                world("world-one", "192.0.2.10"),
                world("world-two", "192.0.2.11"),
            ],
        )
        .unwrap();

        let managed = fs::read_to_string(temp.path().join(".ssh/wt/config")).unwrap();
        insta::assert_snapshot!(
            "remote_worlds_ssh_config",
            normalize_home(&managed, temp.path())
        );
        let evaluated = std::process::Command::new("/usr/bin/ssh")
            .arg("-G")
            .arg("-F")
            .arg(temp.path().join(".ssh/config"))
            .arg("lab.world-one")
            .env("HOME", temp.path())
            .output()
            .unwrap();
        assert!(evaluated.status.success());
        let evaluated = String::from_utf8_lossy(&evaluated.stdout);
        for expected in [
            "hostname 192.0.2.10",
            "user wt",
            "port 22",
            "hostkeyalias lab.world-one",
            "proxyjump wt-server",
        ] {
            assert!(evaluated.lines().any(|line| line == expected), "{expected}");
        }
    }
}
