[Unit]
ConditionPathExists=/run/wt-host-cloud-init

[Service]
Environment=SSH_AUTH_SOCK=/home/wt/.local/state/wt/ssh-agent
ExecStart=
ExecStart=/usr/bin/cloud-init modules --mode=config --file /var/lib/wt-host/user-data
