name: CI

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install --yes libvirt-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --locked -- -D warnings

      - name: Run tests
        run: cargo test --workspace --locked
